version: "3"

#########################################
# REPLACE ALL "password" in public server
#########################################

services:
  # Database
  db:
    platform: linux/x86_64
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysql-dev-network

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mysql-dev-network

networks:
  mysql-dev-network:

volumes:
  db_data: